//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenshinAchievement.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenshinAchievement.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {&quot;0&quot;:{&quot;name&quot;:&quot;天地万象&quot;,&quot;achievements&quot;:[{&quot;id&quot;:80091,&quot;name&quot;:&quot;妖鬼狂言百物语&quot;,&quot;desc&quot;:&quot;集齐全套《鹮巷物语》。&quot;,&quot;reward&quot;:5,&quot;ver&quot;:&quot;2.0&quot;},[{&quot;id&quot;:80127,&quot;name&quot;:&quot;「是想要驯服我吗？」&quot;,&quot;desc&quot;:&quot;使用道具「四方八方之网」捕获1只野外生物。&quot;,&quot;reward&quot;:5,&quot;ver&quot;:&quot;2.3&quot;},{&quot;id&quot;:80128,&quot;name&quot;:&quot;天赐的猎人之手&quot;,&quot;desc&quot;:&quot;使用道具「四方八方之网」捕获30只野外生物。&quot;,&quot;reward&quot;:10,&quot;ver&quot;:&quot;2.3&quot;},{&quot;id&quot;:80129,&quot;name&quot;:&quot;动物园大亨&quot;,&quot;desc&quot;:&quot;使用道具「四方八方之网」捕获100只野外生物。&quot;,&quot;reward&quot;:20,&quot;ver&quot;:&quot;2.3&quot;}],{&quot;id&quot;:81000,&quot;name&quot;:&quot;俯瞰风景&quot;,&quot;desc&quot;:&quot;抵达庆云顶的制高点。&quot;,&quot;reward&quot;:5,&quot;ver&quot;:&quot;1.0&quot;},{&quot;id&quot;:81001,&quot;name&quot;:&quot;烈风的遗骨&quot;,&quot;desc&quot;:&quot;登上风龙废墟的高塔顶端。&quot;,&quot;reward&quot;:5,&quot;ver&quot;:&quot... 的本地化字符串。
        /// </summary>
        internal static string PaimonMoeAchievementJson {
            get {
                return ResourceManager.GetString("PaimonMoeAchievementJson", resourceCulture);
            }
        }
    }
}
